export const NEW_COURIER_START = 'COURIER_START';
export const NEW_COURIER_SUCCESS = 'COURIER_SUCCESS';
export const NEW_COURIER_RESET = 'NEW_PRODUCT_RESET';
export const NEW_COURIER_FAIL = 'COURIER_FAIL';
export const ALL_COURIERS_START = 'ALL_COURIERS_START';
export const ALL_COURIERS_SUCCESS = 'ALL_COURIERS_SUCCESS';
export const ALL_COURIERS_FAIL = 'ALL_COURIERS_FAIL';
export const COURIER_DETAILS_START = 'COURIER_DETAILS_START';
export const COURIER_DETAILS_SUCCESS = 'COURIER_DETAILS_SUCCESS';
export const COURIER_DETAILS_FAIL = 'COURIER_DETAILS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_COURIER_REQUEST = 'UPDATE_COURIER_REQUEST';
export const UPDATE_COURIER_SUCCESS = 'UPDATE_COURIER_SUCCESS';
export const UPDATE_COURIER_RESET = 'UPDATE_COURIER_RESET';
export const UPDATE_COURIER_FAIL = 'UPDATE_COURIER_FAIL';

export const DELETE_COURIER_REQUEST = 'DELETE_COURIER_REQUEST';
export const DELETE_COURIER_SUCCESS = 'DELETE_COURIER_SUCCESS';
export const DELETE_COURIER_RESET = 'DELETE_COURIER_RESET';
export const DELETE_COURIER_FAIL = 'DELETE_COURIER_FAIL';
