export const NEW_DOCUMENT_START = 'DOCUMENT_START';
export const NEW_DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS';
export const NEW_DOCUMENT_RESET = 'NEW_PRODUCT_RESET';
export const NEW_DOCUMENT_FAIL = 'DOCUMENT_FAIL';
export const ALL_DOCUMENTS_START = 'ALL_DOCUMENTS_START';
export const ALL_DOCUMENTS_SUCCESS = 'ALL_DOCUMENTS_SUCCESS';
export const ALL_DOCUMENTS_FAIL = 'ALL_DOCUMENTS_FAIL';
export const DOCUMENT_DETAILS_START = 'DOCUMENT_DETAILS_START';
export const DOCUMENT_DETAILS_SUCCESS = 'DOCUMENT_DETAILS_SUCCESS';
export const DOCUMENT_DETAILS_FAIL = 'DOCUMENT_DETAILS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_COURIER_REQUEST = 'UPDATE_COURIER_REQUEST';
export const UPDATE_COURIER_SUCCESS = 'UPDATE_COURIER_SUCCESS';
export const UPDATE_COURIER_RESET = 'UPDATE_COURIER_RESET';
export const UPDATE_COURIER_FAIL = 'UPDATE_COURIER_FAIL';

export const DELETE_COURIER_REQUEST = 'DELETE_COURIER_REQUEST';
export const DELETE_COURIER_SUCCESS = 'DELETE_COURIER_SUCCESS';
export const DELETE_COURIER_RESET = 'DELETE_COURIER_RESET';
export const DELETE_COURIER_FAIL = 'DELETE_COURIER_FAIL';
